- hosts: webserver
  user: root
  connection: ssh
  become: yes
  tasks:
  - name: Executing webserver role using cron
<<<<<<< HEAD
    cron: name="Executing webserver role using cron" minute="10" hour="5" job="ansible-playbook webserver.yml > root/cron.log"
=======
    cron: name="Executing webserver role using cron" minute="13" hour="5" job="ansible-playbook webserver.yml > /root/cron.log owner=root mode=0777"
>>>>>>> 9729d4c7ee2ded32e2c1c629d57ad4642323d019
