<<<<<<< HEAD
--- #Adding users using loop

=======
>>>>>>> 9729d4c7ee2ded32e2c1c629d57ad4642323d019
- hosts: all
  user: root
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
<<<<<<< HEAD
  - name: Add list of users
=======
  - name: Add a list of users
>>>>>>> 9729d4c7ee2ded32e2c1c629d57ad4642323d019
    user: name={{ item }} state=present group=wheel
    with_items:
      - dhoni
      - virat
<<<<<<< HEAD
      - Raj
      - Rao
      - Madhavan
      - Kalyan
  - name: Remove user from the list
    user: name={{ item }} state=absent
    with_items:
     - virat
     - Raj


   
=======
      - yuvraj
      - paparao
      - kalyan
  - name: Remove the list of users
    user: name={{ item }} state=absent
    with_items:
      - virat
      - yuvraj
>>>>>>> 9729d4c7ee2ded32e2c1c629d57ad4642323d019
